apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multitier-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - migrations-configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - db-statefulset.yaml
  - db-service.yaml

commonLabels:
  app.kubernetes.io/name: multitier-api
  app.kubernetes.io/part-of: multitier-app

images:
  - name: moabdelazem/multitier-api
    newTag: latest
